import streamlit as st 
from ContentChecker import AIContentChecker
## make a title 
st.title("Content Checker")

## add some comments 
st.markdown("This is a simple content checker. It will check if the content is generated by GPTx or not. ")

## fill it with some test content 
test_content = "I hope you are all doing well. I am currently conducting a survey to gather valuable insights and perspectives on a specific topic. I would greatly appreciate your participation in this survey as your input will help shape the direction of this project.\n\nThe survey will only take a few minutes to complete, and your responses will be kept confidential. Your participation in this survey is greatly appreciated and will help us understand the needs and preferences of the community"
## add a text box
content = st.text_area("Enter your content here", test_content)
## add a button
if st.button("Check"):
    ## instantiate the class 
    checker = AIContentChecker(content)
    ## call the check_text method
    checker.check_text()
    ## display the results
    real = checker.real
    fake = checker.fake
    if real > fake:
        st.success(f"The content was generated by a human with {real:.2f}% confidence")
        st.balloons()
    else:
        st.error(f"The content was generated by a GPTx Large Language Model (LLM) with {fake:.2f}% confidence")
        
    